import {
  GetFoodsResponse,
  GetRecipesResponse,
  GetGymsResponse,
} from "@workspace/api-zod";

// The MVP catalogue is intentionally read-only. Nutrition and prices are
// illustrative estimates; operational availability must be confirmed.
export const foods = GetFoodsResponse.parse([
  {
    slug: "paneer-power-bowl",
    name: "Paneer Power Bowl",
    description: "Fresh greens, tender paneer, quinoa and crunchy vegetables with a lemon-herb dressing.",
    category: "Protein Bowls",
    priceInRupees: 149,
    calories: 450,
    proteinG: 28,
    carbsG: 40,
    fatG: 20,
    fiberG: 8,
    portion: "350 g bowl",
    prepMinutes: 12,
    ingredients: ["Paneer", "Cooked quinoa", "Mixed greens", "Cucumber", "Cherry tomatoes", "Lemon-herb dressing"],
    allergens: ["Milk"],
    tags: ["High Protein", "Vegetarian", "No Fry"],
    imageUrl: "/images/salad.jpg",
    vegetarian: true,
    bestFor: ["Build Muscle", "Pre/Post Workout", "Healthy Office Food"],
  },
  {
    slug: "berry-protein-oats",
    name: "Berry Protein Oats",
    description: "Creamy overnight oats with Greek yogurt, seasonal berries and chia seeds.",
    category: "Overnight Oats",
    priceInRupees: 99,
    calories: 320,
    proteinG: 22,
    carbsG: 42,
    fatG: 8,
    fiberG: 7,
    portion: "250 g jar",
    prepMinutes: 8,
    ingredients: ["Rolled oats", "Greek yogurt", "Milk", "Seasonal berries", "Chia seeds"],
    allergens: ["Milk", "Oats may contain gluten"],
    tags: ["High Protein", "Vegetarian", "No Cook"],
    imageUrl: "/images/oats.jpg",
    vegetarian: true,
    bestFor: ["Lose Weight", "Eat for Energy", "Pre/Post Workout"],
  },
  {
    slug: "mediterranean-veggie-bowl",
    name: "Mediterranean Veggie Bowl",
    description: "Chickpeas, crisp vegetables and greens with a bright lemon-tahini dressing.",
    category: "Salads",
    priceInRupees: 129,
    calories: 350,
    proteinG: 14,
    carbsG: 42,
    fatG: 13,
    fiberG: 10,
    portion: "320 g bowl",
    prepMinutes: 10,
    ingredients: ["Cooked chickpeas", "Mixed greens", "Cucumber", "Tomato", "Olives", "Tahini", "Lemon"],
    allergens: ["Sesame"],
    tags: ["Vegan", "No Fry", "High Fiber"],
    imageUrl: "/images/salad.jpg",
    vegetarian: true,
    bestFor: ["Eat Healthy", "Healthy Office Food", "Lose Weight"],
  },
  {
    slug: "chicken-power-salad",
    name: "Chicken Power Salad",
    description: "Cooked chicken, fresh greens and colourful vegetables in a light herb dressing.",
    category: "Salads",
    priceInRupees: 169,
    calories: 380,
    proteinG: 35,
    carbsG: 25,
    fatG: 15,
    fiberG: 7,
    portion: "330 g bowl",
    prepMinutes: 15,
    ingredients: ["Fully cooked chicken breast", "Mixed greens", "Cucumber", "Tomato", "Sweet corn", "Lemon-herb dressing"],
    allergens: [],
    tags: ["High Protein", "Non-Vegetarian", "No Fry"],
    imageUrl: "/images/salad.jpg",
    vegetarian: false,
    bestFor: ["Build Muscle", "Pre/Post Workout", "Lose Weight"],
  },
  {
    slug: "sprouts-protein-salad",
    name: "Sprouts Protein Salad",
    description: "Lightly steamed sprouts, cucumber and tomatoes finished with lemon and fresh coriander.",
    category: "Salads",
    priceInRupees: 89,
    calories: 260,
    proteinG: 18,
    carbsG: 35,
    fatG: 6,
    fiberG: 9,
    portion: "280 g bowl",
    prepMinutes: 10,
    ingredients: ["Steamed moong sprouts", "Cucumber", "Tomato", "Lemon", "Coriander", "Roasted peanuts"],
    allergens: ["Peanuts"],
    tags: ["Vegan", "Under 300 kcal", "No Fry"],
    imageUrl: "/images/salad.jpg",
    vegetarian: true,
    bestFor: ["Lose Weight", "Eat Healthy", "Healthy Office Food"],
  },
  {
    slug: "carrot-orange-juice",
    name: "Carrot Orange Juice",
    description: "A refreshing blend of carrot and orange with a little ginger. No added sugar.",
    category: "Fresh Juices",
    priceInRupees: 69,
    calories: 110,
    proteinG: 2,
    carbsG: 25,
    fatG: 0,
    fiberG: 2,
    portion: "250 ml glass",
    prepMinutes: 5,
    ingredients: ["Carrot", "Orange", "Ginger"],
    allergens: [],
    tags: ["Vegan", "No Added Sugar", "No Cook"],
    imageUrl: "/images/juice.jpg",
    vegetarian: true,
    bestFor: ["Eat for Energy", "Eat Healthy"],
  },
  {
    slug: "green-fresh-juice",
    name: "Green Fresh Juice",
    description: "Cucumber, apple and spinach with a squeeze of lemon and fresh mint.",
    category: "Fresh Juices",
    priceInRupees: 69,
    calories: 90,
    proteinG: 2,
    carbsG: 20,
    fatG: 0,
    fiberG: 2,
    portion: "250 ml glass",
    prepMinutes: 5,
    ingredients: ["Cucumber", "Apple", "Spinach", "Lemon", "Mint"],
    allergens: [],
    tags: ["Vegan", "No Added Sugar", "No Cook"],
    imageUrl: "/images/juice.jpg",
    vegetarian: true,
    bestFor: ["Eat Healthy", "Eat for Energy"],
  },
  {
    slug: "greek-yogurt-fruit-bowl",
    name: "Greek Yogurt Fruit Bowl",
    description: "Thick Greek yogurt, fresh seasonal fruit and a crunchy sprinkle of seeds.",
    category: "Healthy Snacks",
    priceInRupees: 99,
    calories: 210,
    proteinG: 17,
    carbsG: 29,
    fatG: 4,
    fiberG: 3,
    portion: "220 g bowl",
    prepMinutes: 5,
    ingredients: ["Greek yogurt", "Seasonal fruit", "Pumpkin seeds", "Chia seeds"],
    allergens: ["Milk"],
    tags: ["Vegetarian", "No Cook", "Under 300 kcal"],
    imageUrl: "/images/oats.jpg",
    vegetarian: true,
    bestFor: ["Lose Weight", "Eat for Energy", "Healthy Office Food"],
  },
]);

export const recipes = GetRecipesResponse.parse([
  {
    slug: "high-protein-oats",
    youtubeVideoId: "Lkl9_3-jX6c",
    name: "High Protein Overnight Oats",
    description: "A make-ahead breakfast that turns a few everyday ingredients into a satisfying start.",
    category: "Breakfast",
    calories: 320, proteinG: 22, carbsG: 42, fatG: 8, fiberG: 7,
    prepMinutes: 8, difficulty: "Easy", costInRupees: 60, vegetarian: true,
    tags: ["High Protein", "No Cook", "Vegetarian", "Overnight Oats"],
    imageUrl: "/images/oats.jpg",
    ingredients: [
      { name: "Rolled oats", quantity: "40 g" },
      { name: "Greek yogurt", quantity: "150 g" },
      { name: "Milk", quantity: "60 ml" },
      { name: "Seasonal berries", quantity: "50 g" },
      { name: "Chia seeds", quantity: "1 tsp" },
    ],
    steps: ["Combine oats, yogurt, milk and chia seeds in a clean jar.", "Cover and refrigerate for at least 6 hours or overnight.", "Stir, top with berries and enjoy chilled. Keep refrigerated and use within 24 hours."],
  },
  {
    slug: "chickpea-power-salad",
    youtubeVideoId: "UjagvohCxgM",
    name: "Chickpea Power Salad",
    description: "A colourful, crunchy lunch with chickpeas and a simple lemon dressing.",
    category: "Lunch",
    calories: 340, proteinG: 15, carbsG: 43, fatG: 12, fiberG: 10,
    prepMinutes: 10, difficulty: "Easy", costInRupees: 55, vegetarian: true,
    tags: ["Vegan", "No Fry", "Salads", "High Fiber"],
    imageUrl: "/images/salad.jpg",
    ingredients: [
      { name: "Cooked chickpeas", quantity: "150 g" },
      { name: "Cucumber", quantity: "1/2 cup, chopped" },
      { name: "Tomato", quantity: "1, chopped" },
      { name: "Mixed greens", quantity: "1 cup" },
      { name: "Olive oil", quantity: "1 tsp" },
      { name: "Lemon juice", quantity: "1 tbsp" },
    ],
    steps: ["Rinse and drain the cooked chickpeas.", "Combine chickpeas, vegetables and greens in a bowl.", "Whisk lemon juice with olive oil and a pinch of salt; toss with the salad just before serving."],
  },
  {
    slug: "paneer-protein-bowl",
    youtubeVideoId: "wuni1TZcC1g",
    name: "Paneer Protein Bowl",
    description: "A balanced bowl with paneer, quinoa and crisp greens, ready in minutes.",
    category: "Dinner",
    calories: 450, proteinG: 28, carbsG: 40, fatG: 20, fiberG: 8,
    prepMinutes: 12, difficulty: "Easy", costInRupees: 85, vegetarian: true,
    tags: ["High Protein", "Vegetarian", "No Fry"],
    imageUrl: "/images/salad.jpg",
    ingredients: [
      { name: "Paneer", quantity: "100 g" },
      { name: "Cooked quinoa", quantity: "100 g" },
      { name: "Mixed greens", quantity: "1 cup" },
      { name: "Cucumber and tomatoes", quantity: "1 cup" },
      { name: "Lemon juice", quantity: "1 tbsp" },
      { name: "Olive oil", quantity: "1 tsp" },
    ],
    steps: ["Dice the paneer and chop the vegetables.", "Arrange quinoa, paneer, greens and vegetables in a bowl.", "Mix lemon juice and olive oil, season to taste and drizzle over the bowl."],
  },
  {
    slug: "banana-peanut-butter-oats",
    youtubeVideoId: "mjK-ohuJXp8",
    name: "Banana Peanut Butter Oats",
    description: "Creamy oats, sweet banana and peanut butter for an easy, energising breakfast.",
    category: "Breakfast",
    calories: 390, proteinG: 20, carbsG: 48, fatG: 14, fiberG: 8,
    prepMinutes: 8, difficulty: "Easy", costInRupees: 50, vegetarian: true,
    tags: ["High Protein", "No Cook", "Vegetarian", "Overnight Oats"],
    imageUrl: "/images/oats.jpg",
    ingredients: [
      { name: "Rolled oats", quantity: "40 g" },
      { name: "Greek yogurt", quantity: "120 g" },
      { name: "Milk", quantity: "80 ml" },
      { name: "Banana", quantity: "1 small" },
      { name: "Peanut butter", quantity: "1 tbsp" },
    ],
    steps: ["Stir oats, yogurt and milk together in a jar.", "Cover and refrigerate overnight.", "Top with sliced banana and peanut butter before eating. Contains milk and peanuts."],
  },
  {
    slug: "fruit-yogurt-bowl",
    youtubeVideoId: "DHiMpoj6Ulc",
    name: "Fruit & Yogurt Bowl",
    description: "A simple, refreshing snack with Greek yogurt and colourful fruit.",
    category: "Snacks",
    calories: 210, proteinG: 17, carbsG: 29, fatG: 4, fiberG: 3,
    prepMinutes: 5, difficulty: "Easy", costInRupees: 45, vegetarian: true,
    tags: ["Vegetarian", "No Cook", "Low Calorie"],
    imageUrl: "/images/oats.jpg",
    ingredients: [
      { name: "Greek yogurt", quantity: "170 g" },
      { name: "Seasonal fruit", quantity: "80 g" },
      { name: "Chia seeds", quantity: "1 tsp" },
    ],
    steps: ["Spoon the yogurt into a bowl.", "Wash, peel where needed and chop the fruit.", "Top yogurt with fruit and chia seeds. Serve immediately."],
  },
  {
    slug: "carrot-orange-refresher",
    youtubeVideoId: "scHkTHWt3W4",
    name: "Carrot Orange Refresher",
    description: "A fresh, zesty drink made from carrots, oranges and ginger.",
    category: "Drinks",
    calories: 110, proteinG: 2, carbsG: 25, fatG: 0, fiberG: 2,
    prepMinutes: 5, difficulty: "Easy", costInRupees: 35, vegetarian: true,
    tags: ["Vegan", "No Cook", "No Added Sugar"],
    imageUrl: "/images/juice.jpg",
    ingredients: [
      { name: "Carrot", quantity: "1 medium" },
      { name: "Orange", quantity: "1 large" },
      { name: "Ginger", quantity: "1 cm piece" },
      { name: "Water", quantity: "50 ml, as needed" },
    ],
    steps: ["Wash the carrot and ginger; peel the orange and remove seeds.", "Blend ingredients with water until smooth.", "Serve fresh. Leave unstrained for more fibre."],
  },
]);

// These are clearly labelled example listings in the UI, not verified partners.
export const gyms = GetGymsResponse.parse([
  { id: "fitzone-madhapur", name: "FitZone Gym", locality: "Madhapur", city: "Hyderabad", address: "Madhapur, Hyderabad", distanceKm: 1.2, openingHours: "6:00 AM – 10:00 PM", categories: ["Salads", "Overnight Oats", "Fresh Juices"] },
  { id: "core-gachibowli", name: "Core Fitness", locality: "Gachibowli", city: "Hyderabad", address: "Gachibowli, Hyderabad", distanceKm: 3.4, openingHours: "5:30 AM – 10:00 PM", categories: ["Protein Bowls", "Healthy Snacks", "Fresh Juices"] },
  { id: "move-banjara", name: "Move Studio", locality: "Banjara Hills", city: "Hyderabad", address: "Banjara Hills, Hyderabad", distanceKm: 6.5, openingHours: "6:00 AM – 9:00 PM", categories: ["Salads", "Protein Bowls", "Overnight Oats"] },
]);
